### ISSUE TITLE
Translate pt-BR o README

### ISSUE THREAD

**Issue by ghost** [Valdjr/team-organizer-backend#13]
I wonder if I can translate README for you without any problem.
Would ?

**Comment by rodrigogsn** [comment]
> I wonder if I can translate README for you without any problem.
> Would ?

That would be awesome Luan. We already have an article on Product Hunt in english, you can use references there if you like.
https://www.producthunt.com/posts/teammaker-v2/

**Comment by luansoarees** [comment]
#  TeamMaker

Ola pessoal! Sou um dos fundadores do TeamMaker: uma plataforma que analisa os dados do usuário e agrupa automaticamente as pessoas nas equipes mais adequadas possíveis!

##  O que é o TeamMaker?

Essa ferramenta funciona para empresas ou eventos que envolvem muitas pessoas que precisam ser colocadas em equipes.
O TeamMaker classificará automaticamente essas pessoas em equipes equilibradas, com base nos dados profissionais fornecidos, como habilidades e experiências de trabalho.

##  Tecnologias

Nosso projeto está em desenvolvimento.
Estamos usando as versões mais recentes do NodeJS e ReactJS em nosso código, oferecendo desempenho de alta velocidade.
Está atualmente hospedado no Heroku.
---
- [Node.js](https://nodejs.org/en/)
- [React](https://reactjs.org)

##  Por que nós?

Esta plataforma está sendo desenvolvida para a primeira hackathon online brasileira chamada ** Open Hack ** , realizada por ** Shawee ** .
Durante o primeiro dia do concurso, percebemos o quão difícil era fazer uma equipe online.
Nos apresentaríamos principalmente dentro de um canal dedicado ao Discord, e procuraríamos pessoas com habilidades semelhantes e também profissionais de diferentes áreas, tentando encontrar equilíbrio em um grupo de cinco membros.

##  Como contribuir

- Faça um fork desse repositório;
- Cria a branch com sua feature: `git checkout -b minha-feature`;
- Faça commit das suas alterações: `git commit -m 'feat: Minha nova feature'`;
- Faça push para a sua branch: `git push origin minha-feature`.

Depois que o merge da sua pull request for feito, você pode deletar a sua branch.


##  O problema era ...

Os canais estavam cheios de apresentações e bate-papos, e era muito difícil acompanhar a conversa, e por algum tempo os usuários precisavam copiar sua biografia escrita agora para outras pessoas, já que não há lugar apropriado para fazer isso dentro do Discord.

Era cansativo procurar pessoas em uma barra lateral cheia de centenas de apelidos e fotos que não diziam exatamente ao competidor quem eles realmente são ou o que realmente fazem.

##  O que esperamos

O TeamMaker é uma resposta para esse problema. A mesma plataforma que oferece a inscrição dos usuários também os organizará por um número de pontuação com base em suas habilidades e na duração de sua experiência profissional. O robô TeamMaker calculará números e colocará os usuários nas equipes para que a pontuação total da equipe fique equilibrada.

Dessa forma, o evento pode evitar automaticamente equipes com apenas desenvolvedores internos ou equipes com apenas os profissionais mais experientes. E o sistema pode ser usado não apenas em hackathons, mas em qualquer caso que tenha centenas de pessoas trabalhando em atividades diferentes.

## :memo: Licença

Esse projeto está sob a licença MIT. Veja o arquivo [LICENSE](LICENSE.md) para mais detalhes.

**Comment by carloshenriquecarniatto** [comment]
I am haved analysed this and maked merge!
